Usability improvements
gpt-engineer-org/gpt-engineer pull request #1191
Opened 2024-07-23 19:58 UTC by jtoberling

- Improvement mode toml filelist have to be in full-path sorted mode. 
  By using large project the current listing is "mixed" and very hard to use. 

- Increasing timeout value in chat_to_files finditer. 
  By using DeepSeek API with "deepseek-coder" model without this timeout increment the resolution of completion is timing out quite frequently.

- Adding "--skip-file-selection" / "-s" command line option to skip toml file selection editor in improvement mode.
  By using it in complex projects and repetitive tasks the file selector popup is especially disturbing and against usabilty. 

Please consider to merge the above points as they are leading to a more smooth usability experiment.

2024-07-26 01:01 UTC, similato87 requested changes
Great job overall! The implementation looks solid, and the functionality is well thought out. The main thing needed now is to add tests. You can find the test cases [test_main.py](https://github.com/gpt-engineer-org/gpt-engineer/blob/main/tests/applications/cli/test_main.py). Since there isn't a specific test case for the file selector, please write some tests for the main process to ensure everything passes.

2024-07-26 01:03 UTC, similato87 commented
> * Improvement mode toml filelist have to be in full-path sorted mode.
>   By using large project the current listing is "mixed" and very hard to use.
> * Increasing timeout value in chat_to_files finditer.
>   By using DeepSeek API with "deepseek-coder" model without this timeout increment the resolution of completion is timing out quite frequently.
> * Adding "--skip-file-selection" / "-s" command line option to skip toml file selection editor in improvement mode.
>   By using it in complex projects and repetitive tasks the file selector popup is especially disturbing and against usabilty.
> 
> Please consider to merge the above points as they are leading to a more smooth usability experiment.

@jtoberling Thank you for your meaningful contributions! Your efforts have significantly impacted us, and we truly appreciate your dedication. We love having talented and passionate contributors like you on the team. Keep up the great work!

2024-07-27 19:29 UTC, jtoberling commented on gpt_engineer/core/chat_to_files.py
Defaulted to 3 secs. 
Added a new command line parameter "--diff_timeout INTEGER" to override. 
Also created some test in tests/application/cli/test_main.py:test_improve_existing_project_diff_timeout for the new command line option.

2024-07-27 19:31 UTC, jtoberling commented on gpt_engineer/applications/cli/main.py
Added test:
-  tests/application/cli/test_main.py:test_improve_existing_project_skip_file_selection

2024-07-27 19:32 UTC, jtoberling commented on gpt_engineer/applications/cli/file_selector.py
Added tests:
- tests/core/test_file_selector_enhancements.py: test_file_selector_enhancement_skip_file_selector
- tests/core/test_file_selector_enhancements.py: test_file_selector_enhancement_sort

2024-07-27 19:33 UTC, jtoberling commented on gpt_engineer/tools/supported_languages.py
Also added Arduino *.ino files. They are basically C++ with some extra functions like "setup()" and  "loop()" - works well with ChatGPT & DeepSeek.

2024-07-28 15:11 UTC, similato87 commented on gpt_engineer/core/chat_to_files.py
Great work on defaulting time and adding the new command line parameter for overriding. The test you created for this is a nice addition.

2024-07-28 15:12 UTC, similato87 commented on gpt_engineer/applications/cli/file_selector.py
Thanks for adding the tests for the file selector enhancements. I appreciate your thoroughness in testing both skipping and sorting.

2024-07-28 15:13 UTC, similato87 commented on gpt_engineer/applications/cli/main.py
Valuable enhancement. Thanks for covering this aspect.

2024-07-28 15:13 UTC, similato87 commented on gpt_engineer/tools/supported_languages.py
Including the Arduino *.ino files was a smart move. It's good to know they integrate well with ChatGPT & DeepSeek.

2024-07-28 15:14 UTC, similato87 commented
@jtoberling I fully agree with the changes you’ve made and approve this PR. We'll discuss this further in our next group meeting. Great job!

2024-07-28 15:17 UTC, similato87 approved these changes
I fully agree with the meaningful enhancements for skipping file selection and adding buffer time for large codebases. The extended support for more languages, including Arduino files, is a great addition. Everything is well-designed and clearly tested.

2024-08-08 17:27 UTC, merged